-- Auto-generated from schema-map-postgres.yaml (map@sha1:F0EE237771FBA8DD7C4E886FF276F91A862C3718)
-- engine: postgres
-- table:  migration_events

CREATE TABLE IF NOT EXISTS migration_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_name VARCHAR(120) NOT NULL,
  from_version VARCHAR(64) NULL,
  to_version   VARCHAR(64) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  started_at   TIMESTAMPTZ(6) NULL,
  finished_at  TIMESTAMPTZ(6) NULL,
  error TEXT NULL,
  meta JSONB NULL,
  CONSTRAINT chk_mig_status CHECK (status IN ('pending','running','done','failed','cancelled'))
);
